name: Build & Push Backend Despachos Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'back-Despachos_SpringBoot/**'
      - '.github/workflows/despachos.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build y Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          file: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO/Dockerfile
          push: true
          tags: |
            ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
            ${{ secrets.ECR_REPO_URL_BACKEND }}:${{ github.sha }}