name: Build, Push & Deploy Frontend Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'front_despacho/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build y Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho
          file: ./front_despacho/Dockerfile
          push: true
          tags: |
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}

      - name: Esperar propagación ECR
        run: sleep 15

      - name: Deploy Frontend en EC2 usando SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_FRONTEND_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Frontend" \
            --parameters commands='[
              "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | sudo docker login --username AWS --password-stdin '${{ secrets.ECR_REGISTRY }}'",
              "sudo docker pull '${{ secrets.ECR_REPO_URL_FRONTEND }}':latest",
              "sudo docker stop frontend || true",
              "sudo docker rm frontend || true",
              "sudo docker run -d --name frontend --restart always -p 80:80 '${{ secrets.ECR_REPO_URL_FRONTEND }}':latest"
            ]'